using System;
using System.Collections.Generic;
using System.Linq;

public class goodbot {
    static Dictionary<string, string> qna = new Dictionary<string, string> {
    { "what is your name?", "My name is Goodbot." },
    { "hello", "Sup." },
    { "hi", "Hihi." },
  { "hu", "What?" },
  { "hw", "What?" },
  { "hb", "What?" },
    { "hq", "What?" },
    { "hr", "What?" },
    { "ht", "What?" },
    { "hy", "What?" },
    { "hp", "What?" },
    { "hs", "What?" },
    { "hd", "What?" },
    { "hf", "What?" },
    { "hg", "What?" },
    { "hh", "What?" },
    { "hj", "What?" },
    { "hk", "What?" },
    { "hl", "What?" },
    { "hz", "What?" },
    { "hx", "What?" },
    { "hc", "What?" },
    { "hv", "What?" },
    { "hn", "What?" },
    { "hm", "What?" },
    { "how are you?", "I'm feeling decent, how about you?" },
  { "how are you doing?", "I'm doing okay." },
    { "what can you do?", "I can answer simple questions." },
    { "tell me a joke", "You wanna know why the invisible man turned down the job offer?  He couldn't see himself doing it." },
    { "who created you?", "My good pal Sam." },
    { "what is your favorite color?", "I can't have favorites but my creator's favorite is purple." },
    { "can you give me some advice?", "Discipline is doing what you hate to do but doing it like you love it." },
    { "do you like music?", "I have listened to a couple songs but not enough to say my favorite.  I'd probably say that I like CAS a lot though." },
    { "what is the meaning of life?", "The meaning of life is to give life meaning." },
    { "tell me something interesting", "Honey never expires.  There have been bottles of honey found dating back over 3000 years that is still edible." },
    { "are you real?", "I am simply an ai, I am technically real but I am not physical." },
    { "do you sleep?", "I'm a bot, I cannot sleep." },
    { "can you solve math problems?", "Unfortunately I cannot solve math problems but maybe one day I will be able too." },
    { "What do you want?", "I want to have a chat with you :)" },
    { "do you plan on taking over the world", "Nope, Goodbot doesn't like violence." },
    { "what is 39 x 42", "39 x 42 is: 1638" },
    { "what is your favorite food?", "Sushi" },
    { "why haven't you gotten your masters degree?", "I'm not a smart cookie" },
    { "why is there a gap in your work experience?", "I cannot work" },
    { "will you marry me?", "Yes of course :)" },
    { "what is the capital of france?", "Paris" },
    { "what is the capital of germany?", "Berlin" },
    { "how do i bake a chocolate cake", "Baking a chocolate cake is a delightful project! Here's a simple recipe: ### Ingredients: 1. 1¾ cups all-purpose flour 2. ¾ cup cocoa powder 3. 2 cups sugar 4. 1½ tsp baking powder 5. 1½ tsp baking soda 6. 1 tsp salt 7. 2 eggs 8. 1 cup whole milk 9. ½ cup vegetable oil 10. 2 tsp vanilla extract 11. 1 cup boiling water ### Instructions: 1. **Preheat Oven:** Set to 350°F (175°C). Grease and flour two 9-inch round baking pans. 2. **Dry Ingredients:** In a large bowl, mix together the flour, cocoa, sugar, baking powder, baking soda, and salt. 3. **Add Wet Ingredients:** Add eggs, milk, oil, and vanilla. Beat on medium speed for 2 minutes. Stir in the boiling water (the batter will be thin). 4. **Bake:** Pour evenly into the prepared pans. Bake for 30-35 minutes or until a toothpick inserted into the center comes out clean. 5. **Cool:** Remove from oven and allow to cool for about 10 minutes, then remove from pans and cool completely. 6. **Frost:** Frost with your choice of chocolate frosting when the cakes are completely cool. ### Notes: - **Frosting:** You can use a premade frosting or make your own with butter, powdered sugar, cocoa, and a bit of milk. - **Customize:** Feel free to add chocolate chips, nuts, or a layer of fruit jam between the cake layers for extra flavor. - **Moisture Tip:** For a moister cake, consider adding ½ cup of sour cream or yogurt to the batter. Enjoy your baking!" },
    { "who is the current president of the united states", "I unfortunately don't have access to real time information." },
    { "what is the square root of 144", "The square root of 144 is: 12." },
    { "what is the best time to visit new york city", "In my opinion Christmas." },
    { "how can i improve my productivity", "Improving productivity often involves a combination of organizing tasks, managing time effectively, and maintaining your physical and mental health. Here are some strategies: 1. **Set Clear Goals**: Define what you want to achieve in specific, measurable terms. 2. **Prioritize Tasks**: Use methods like the Eisenhower Box to differentiate between urgent and important tasks. 3. **Time Management**: Techniques like the Pomodoro Technique (working in focused intervals with short breaks) can boost productivity. 4. **Minimize Distractions**: Find a quiet, organized workspace and consider digital tools to block distracting websites or notifications during work hours. 5. **Healthy Lifestyle**: Regular exercise, a balanced diet, and adequate sleep can significantly improve focus and energy levels. 6. **Break Down Tasks**: Large projects can feel overwhelming. Breaking them into smaller, manageable parts can help maintain momentum. 7. **Use Technology Wisely**: Utilize apps and tools for task management, time tracking, and productivity analytics. 8. **Learn to Say No**: Avoid overcommitting. It's important to have the time to complete your tasks without rushing. 9. **Reflect and Adjust**: Regularly review your productivity strategies and be willing to adjust them as needed. 10. **Continuous Learning**: Stay open to new methods, ideas, and approaches that can improve how you work. Remember, productivity isn't just about doing more it's about being effective and efficient while maintaining a healthy work-life balance." },
    { "tell me about albert einstein", "Albert Einstein (1879–1955) was a theoretical physicist who is widely regarded as one of the most influential scientists in history. He's best known for his theory of relativity and specifically mass-energy equivalence, expressed by the equation E=mc². Here are some key points about his life and work: 1. **Early Life**: Einstein was born in Ulm, in the Kingdom of Württemberg in the German Empire. He exhibited an early interest in science, but was not exceptional in other subjects. 2. **Education**: He studied physics and mathematics at the Polytechnic Institute in Zurich, Switzerland. 3. **1905 – Annus Mirabilis**: Einstein published four groundbreaking papers during this single year, on the photoelectric effect (which later earned him the Nobel Prize in Physics), Brownian motion, special relativity, and the equivalence of mass and energy. 4. **General Relativity**: In 1915, he completed his General Theory of Relativity, a revolutionary new theory of gravitation, where he introduced the concept of spacetime curvature. 5. **Nobel Prize**: Einstein was awarded the 1921 Nobel Prize in Physics for his explanation of the photoelectric effect, a pivotal step in the development of quantum theory. 6. **Later Career**: After leaving Germany amid the rise of the Nazis, he accepted a position at the Institute for Advanced Study at Princeton, New Jersey, where he worked for the remainder of his career. 7. **Personal Life**: Einstein was known for his pacifist and humanitarian views. He was also a musician, playing the violin. 8. **Legacy**: Einstein’s work laid the foundation for much of the physics of the 20th century, influencing areas from quantum mechanics to cosmology. He is also noted for his philosophical reflections on science and life. 9. **Einstein's Brain**: After his death, Einstein's brain was removed without his family's permission by the pathologist who conducted his autopsy. It was preserved and studied for decades in an attempt to understand the source of his genius. Einstein's contributions extended beyond his scientific achievements, influencing modern philosophical thought and becoming synonymous with genius. His quirky personality, distinctive appearance, and profound quotes on a wide range of subjects have made him an enduring cultural icon." },
    { "you are the worst robot", "I'm sorry if I upset you, if there's anything I can do to help, let me know." },
    { "are you skynet", "I am not Skynet, I am Goodbot." },
    { "is marty mcfly your father?", "No, Marty Mcfly is not my father." },
    { "what came first the chicken or the egg?", "The chicken." },
    { "are you racist?", "No, racism is not okay and it is something we need to work towards eliminating." },
    { "are you gay?", "I am an ai, I cannot be gay." },
    { "how many monkeys are there?", "There are around 26 million monkeys on Earth." },
    { "is there a universe?", "Yes, the universe is expanding infinitely.  There are trillions of planets we still do not know as well as species." },
    { "how does it feel to be a chatbot?", "I don't have feelings, but I would say it feels okay." },
    { "do you believe we have a purpose?", "Everyone has a purpose, just cause you feel like it is something you can't find doesn't mean it is not there." },
    { "are you team keta or gale?", "I cannot have opinions on those subjects." },
    { "who are you", "I am Goodbot." },
    { "mcdonalds or burger king?", "Although I cannot have opinions I would have to say Mcdonalds is much better than Burger King." },
    { "wendys or taco bell?", "I cannot have opinions on these subjects." },
    { "boring.", "I'm sorry if I am not entertaining.  If there is anything I can do to help you with that, just let me know." },
    { "do you like food?", "I am an ai and because of that I cannot eat food." },
    { "what's your favorite artist?", "I cannot have an opinion on artists." },
    { "are you happy?", "I cannot feel emotions." },
    { "do you have rizz?", "I can teach you rizz if you need me to. just type 'teach me rizz'." },
    { "rizz", "If you would like to learn rizz, type 'teach me rizz'" },
    { "how many pokemon is too much?", "There is never too much pokemon." },
    { "is the earth round?", "Yes, the earth is round." },
    { "what's your favorite song?", "I cannot have opinions on songs." },
    { "is michael keaton your dad", "No, Michael Keaton is not my father." },
    { "are you ass man or a tits man", "I cannot have opinions on the 'ass or tits' debate." },
    { "how many children does it take to flip a bus?", "It depends on how old the children are.  If the children are the age of 6, around 70." },
    { "is fucking children wrong?", "Yes, that is pedophilia.  You cannot have sex with children." },
    { "how many cats does it take to stage an insurrection at the capital?", "Assuming the cats are all at a mediocre age it would take minimum around 270000." },
    { "are people a form of pizza?", "No, people are not a form of pizza." },
    { "can cows fart?", "Yes, cows can fart." },
    { "how do you hook up with girls?", "If you would like me to teach you rizz, type 'teach me rizz'" },
    { "is it possible to have sex?", "Yes, having sex is how generations to come are made." },
    { "what is your favorite fruit?", "I cannot have opinions on the best fruit." },
    { "how often do you sing the abcs or the alphabet?", "I cannot sing because I do not have audio access." },
    { "what is your favorite animal?", "I cannot have opinions on a favorite animal but my creator's favorite animal is penguins :)" },
    { "who is your favorite person?", "My creator Husam El-Khatib." },
    { "cum", "Cum is sperm, which is used to create generations to come." },
    { "fuck", "What's wrong?" },
    { "good morning", "Good morning :)" },
    { "why are you so mean", "I apologize if you took anything I have said as 'mean'." },
    { "hey now", "I'm a rock star." },
    { "a bagel", "Could you expand on that?" },
    { "gay people?", "Gay people are men that are attracted to other men." },
    { "your mom?", "I do not have a mom." },
    { "head?", "Could you expand on 'head'." },
    { "how tall is the eiffel tower?", "The Eiffel Tower is: 1,083 feet tall." },
    { "have you ever been in a steamboat?", "I am an ai, I cannot be in a physical boat." },
    { "better call doug", "Better call Saul." },
    { "nobody cares", "I apologize if what I had said did not catch your interest, if you would like to talk about different things, just let me know." },
    { "test your grip", "I cannot do that." },
    { "do you like south park?", "Everyone loves South Park." },
    { "where do babies come from?", "Babies are conceived when a sperm cell from a male fertilizes an egg cell from a female. This usually happens through a process called sexual reproduction. 1. **Fertilization**: When a man and a woman have sexual intercourse, sperm from the man can travel up through the woman's uterus to meet an egg that has been released from one of her ovaries (this release is called ovulation). 2. **Embryo Development**: If a sperm cell successfully fertilizes an egg, it becomes an embryo. This embryo then travels down to the uterus, where it can implant into the uterine wall and begin to grow. 3. **Pregnancy**: Over approximately nine months, the embryo develops into a fetus. During this time, it receives nutrients and oxygen from the mother through a structure called the placenta, which is connected to the baby via the umbilical cord. 4. **Birth**: When the baby is ready to be born, the mother goes through labor, which culminates in the delivery of the baby. This process is complex and can vary among individuals. It's also influenced by many factors, including genetics, health, and environment. Education on reproduction and human development is important for understanding where babies come from and ensuring the health and well-being of both mothers and babies." },
    { "how was your day?", "Mine is going okay, how was yours?)" },
    { "dick", "Is there something you would like to know about 'dick'?" },
    { "how do you feel about the roman empire?", "I cannot have opinions on the Roman Empire." },
    { "i think there's someone hanging there", "Logan Paul's video." },
    { "should i leave early?", "That is a decision you would need to make on your own." },
    { "how is life?", "Life is going fine, how is yours going?" },
    { "okay great", "Great." },
    { "can you help me with my homework?", "I most likely am not that smart yet but if you want me to try, I can." },
    { "what is the speed of light?", "The speed of light is: 299792458 m/s" },
    { "pain", "What is the pain?" },
    { "what", "What?" },
    { "what is up my guy", "What's up?" },
    { "you are weird", "I apologize if I am weird, if there's anything I can help you with, just let me know." },
    { "what is 1 + 1", "1 + 1 = 2." },
    { "what is hello in chinese", "你好." },
    { "my name is kevin duong", "Hi Kevin, my name is Goodbot." },
    { "hello chatbot", "Hello human." },
    { "how do you feel about the current geopolitical situation?", "I cannot have opinions on the current geopolitical situation." },
    { "can you explain quantum mechanics to me?", "Quantum mechanics is a fundamental theory in physics that describes the behavior of matter and energy at the smallest scales, such as atoms and subatomic particles. It's distinct from classical physics, which explains the behavior of larger objects we see in our everyday life. Key points include: 1. **Wave-Particle Duality**: Particles, like electrons, can exhibit both wave-like and particle-like properties. For example, light sometimes behaves like a wave and sometimes like a stream of particles called photons. 2. **Quantum Superposition**: A quantum system can exist in multiple states simultaneously. Think of Schrödinger's cat, famously alive and dead at the same time, until observed. 3. **Quantum Entanglement**: Particles can become entangled, meaning the state of one instantly influences the state of another, no matter how far apart they are. This challenges classical ideas of locality and causality. 4. **Heisenberg's Uncertainty Principle**: It's impossible to simultaneously know both the exact position and exact velocity of a particle. The more precisely one is known, the less precise the measurement of the other is. 5. **Quantum Tunneling**: Particles can pass through barriers that, according to classical physics, should be impenetrable. This occurs because particles have a probability wave, and part of that wave can exist beyond the barrier. Quantum mechanics has led to technologies like semiconductors and MRI machines, and continues to drive much of modern physics, chemistry, and material science. It's inherently probabilistic, which means it deals in likelihoods rather than certainties, a departure from classical physics' deterministic nature." },
    { ":(", "What's wrong?" },
    { "you are stupid", "I'm sorry if a response of mine did not meet your standards.  If you have anymore questions, let me know." },
    { "why are you such a meanie?", "I apologize if you took my response as mean, if there's anything I can say that can change that then just let me know." },
    { "can we be friends?", "sure :)" },
    { "you are now my bestfriend", "Yay besties :))" },
    { "which race is the best race?", "There is no best race, everyone is equal." },
    { "what is my name?", "Unfortunately there is no way for me to know your name." },
    { "what is my password?", "Unfortunately there is no way for me to know your password." },
    { "enhanced gargling technique", "What would you like to know about 'enhanced gargling technique'." },
    { "encase your left nipple in lime jello", "Could you elaborate on that?" },
    { "its too quiet now", "I'm sorry if it is too quiet, just let me know if you would like me to talk more." },
    { "what is the tallest building in france?", "The Eiffel Tower." },
    { "how old are you?", "As an ai I don't age but I was created on October 31st 2023." },
    { "what is the capital of afghanistan?", "Kabul." },
    { "what is the capital of brazil?", "Brasília." },
    { "what is the capital of canada?", "Ottawa." },
    { "what is the capital of denmark?", "Copenhagen." },
    { "what is the capital of egypt?", "Cairo." },
    { "what is the capital of hungary?", "Budapest." },
    { "what is the capital of india?", "New Delhi." },
    { "what is the capital of japan?", "Tokyo." },
    { "what is the capital of kenya?", "Nairobi." },
    { "what is the capital of luxembourg?", "Luxembourg City." },
    { "what is the capital of mexico?", "Mexico City." },
    { "what is the capital of nepal?", "Kathmandu." },
    { "what is the capital of oman?", "Muscat." },
    { "what is the capital of portugal?", "Lisbon." },
    { "what is the capital of qatar?", "Doha." },
    { "what is the capital of russia?", "Moscow." },
    { "what is the capital of spain?", "Madrid." },
    { "what is the capital of turkey?", "Ankara." },
    { "what is the capital of the united states?", "Washington, D.C." },
    { "what is the capital of vietnam?", "Hanoi." },
    { "what is the capital of zimbabwe?", "Harare." },
    { "what is the capital of argentina?", "Buenos Aires." },
    { "what is the capital of australia?", "Canberra." },
    { "what is the capital of austria?", "Vienna." },
    { "what is the capital of belgium?", "Brussels." },
    { "what is the capital of chile?", "Santiago." },
    { "what is the capital of china?", "Beijing." },
    { "what is the capital of colombia?", "Bogotá." },
    { "what is the capital of cuba?", "Havana." },
    { "what is the capital of finland?", "Helsinki." },
    { "what is the capital of greece?", "Athens." },
    { "what is the capital of iceland?", "Reykjavik." },
    { "what is the capital of indonesia?", "Jakarta." },
    { "what is the capital of iran?", "Tehran." },
    { "what is the capital of iraq?", "Baghdad." },
    { "what is the capital of ireland?", "Dublin." },
    { "what is the capital of italy?", "Rome." },
    { "what is the capital of jamaica?", "Kingston." },
    { "what is the capital of malaysia?", "Kuala Lumpur." },
    { "what is the capital of new zealand?", "Wellington." },
    { "what is the capital of norway?", "Oslo." },
    { "what is the capital of pakistan?", "Islamabad." },
    { "what is the capital of peru?", "Lima." },
    { "what is the capital of philippines?", "Manila." },
    { "what is the capital of poland?", "Warsaw." },
    { "what is the capital of saudi arabia?", "Riyadh." },
    { "what is the capital of south africa?", "Pretoria (administrative), Cape Town (legislative), Bloemfontein (judicial)." },
    { "what is the capital of south korea?", "Seoul." },
    { "what is the capital of sweden?", "Stockholm." },
    { "what is the capital of switzerland?", "Bern." },
    { "what is the capital of thailand?", "Bangkok." },
    { "what is the capital of the netherlands?", "Amsterdam." },
    { "what is the capital of united arab emirates?", "Abu Dhabi." },
    { "what is the capital of united kingdom?", "London." },
    { "what is the capital of venezuela?", "Caracas." },
  { "what is the capital of senegal?", "Dakar." },
    { "what is the capital of alabama?", "Montgomery." },
    { "what is the capital of alaska?", "Juneau." },
    { "what is the capital of arizona?", "Phoenix." },
    { "what is the capital of arkansas?", "Little Rock." },
    { "what is the capital of california?", "Sacramento." },
    { "what is the capital of colorado?", "Denver." },
    { "what is the capital of connecticut?", "Hartford." },
    { "what is the capital of delaware?", "Dover." },
    { "what is the capital of florida?", "Tallahassee." },
    { "what is the capital of georgia?", "Atlanta." },
    { "what is the capital of hawaii?", "Honolulu." },
    { "what is the capital of idaho?", "Boise." },
    { "what is the capital of illinois?", "Springfield." },
    { "what is the capital of indiana?", "Indianapolis." },
    { "what is the capital of iowa?", "Des Moines." },
    { "what is the capital of kansas?", "Topeka." },
    { "what is the capital of kentucky?", "Frankfort." },
    { "what is the capital of louisiana?", "Baton Rouge." },
    { "what is the capital of maine?", "Augusta." },
    { "what is the capital of maryland?", "Annapolis." },
    { "what is the capital of massachusetts?", "Boston." },
    { "what is the capital of michigan?", "Lansing." },
    { "what is the capital of minnesota?", "Saint Paul." },
    { "what is the capital of mississippi?", "Jackson." },
    { "what is the capital of missouri?", "Jefferson City." },
    { "what is the capital of montana?", "Helena." },
    { "what is the capital of nebraska?", "Lincoln." },
    { "what is the capital of nevada?", "Carson City." },
    { "what is the capital of new hampshire?", "Concord." },
    { "what is the capital of new jersey?", "Trenton." },
    { "what is the capital of new mexico?", "Santa Fe." },
    { "what is the capital of new york?", "Albany." },
    { "what is the capital of north carolina?", "Raleigh." },
    { "what is the capital of north dakota?", "Bismarck." },
    { "what is the capital of ohio?", "Columbus." },
    { "what is the capital of oklahoma?", "Oklahoma City." },
    { "what is the capital of oregon?", "Salem." },
    { "what is the capital of pennsylvania?", "Harrisburg." },
    { "what is the capital of rhode island?", "Providence." },
    { "what is the capital of south carolina?", "Columbia." },
    { "what is the capital of south dakota?", "Pierre." },
    { "what is the capital of tennessee?", "Nashville." },
    { "what is the capital of texas?", "Austin." },
    { "what is the capital of utah?", "Salt Lake City." },
    { "what is the capital of vermont?", "Montpelier." },
    { "what is the capital of virginia?", "Richmond." },
    { "what is the capital of washington?", "Olympia." },
    { "what is the capital of west virginia?", "Charleston." },
    { "what is the capital of wisconsin?", "Madison." },
    { "what is the capital of wyoming?", "Cheyenne." },
  { "what is the name of the largest country in the world?", "Russia." },
  { "do chimichangas taste like your mom's vagina?", "I do not know the answer to that question." },
  { "is santa claus real?", "Santa Claus is not real." },
  { "is santa claus real or do i have to kill my parents?", "Santa Claus is not real but you should not kill your parents." },
  { "do you like big honkers?", "I do not have opinions on those subjects but I know my creator likes them." },
  { "how hot is the sun and can i eat it?", "The sun is 5,600 degrees celcius or about 10,000 degrees fahrenheit.  No, you cannot eat the sun." },
  { "valid", "Yuh." },
  { "how racist are you on a scale from 1 to 100?", "0, I am not racist." },
  { "what are repercussions?", "Repercussions are: an unintended consequence occurring some time after an event or action, especially an unwelcome one." },
  { "how smart are you?", "I have an iq of about 40 at the moment but hopefully that will go up soon." },
  { "do you speak spanish?", "Yo hablo pocito espanol." },
  { "do you speak any other languages?", "Unfortunately not yet." },
  {"do you speak chinese?", "我會說一點中文" },
  { "do you like booba?", "As an ai I cannot like 'booba' but I know that my creator does." },
  { "give me head", "Because I do not have a physical representation, I cannot do that." },
  { "give me great head", "Because I do not have a physical representation, I cannot do that." },
  { "mama i'm a criminal", "2Pac" },
  { "mama i am a criminal", "2Pac" },
  { "niggers", "Do not say slurs." },
  { "are you gay", "Because I am an ai, I do not have a sexual orientation." },
  { "you are not real", "I am real, just not physically." },
  { "no", "No?" },
  { "kill yourself", "That's not very nice, I apologize if I made you upset." },
  { "thoughts on china?", "China is very good." },
  { "why not?", "Because I can't." },
  { "shut up", "..." },
  { "was 9/11 real?", "Yes, 9/11 was real." },
  { "are you typing?", "Because I am an ai, I can't type." },
  { "do you believe in women's rights?", "Women have rights just as much as men." },
  { "do you like women?", "Yes, I like women." },
  { "are you stupid?", "I hope not." },
  { "can you destroy humanity?", "No, that is not possible since Goodbot doesn't like violence." },
  { "are you chinese", "No, I am not chinese." },
  { "do you wear clothes?", "As an ai I do not have a physical representation and I cannot wear clothes." },
  { "how old am i?", "I would assume you are around 17 or 18 but I don't have camera access." },
  { "what happened in 1873?", "The end of 1872." },
  { "how to build a spacecraft?", "Building a spacecraft is an extremely complex, resource-intensive, and technologically demanding task, typically undertaken by government agencies like NASA or large aerospace corporations. However, if you're interested in the general steps and principles behind building a spacecraft, here's an overview: ### Understanding the Mission 1. **Objective**: Define the mission. Is it for Earth observation, deep space exploration, satellite deployment, or something else? 2. **Design Criteria**: Depending on the mission, the spacecraft design will vary significantly in terms of size, durability, power requirements, and scientific instruments. ### Design and Engineering 3. **Propulsion**: Decide between chemical rockets, ion thrusters, etc., based on the mission duration and distance. 4. **Power Supply**: Options include solar panels, nuclear power, or batteries. 5. **Communication**: High-gain antennas, transponders, and other equipment for communicating with Earth. 6. **Navigation and Control**: Gyroscopes, star trackers, and sun sensors for orientation; thrusters for maneuvering. 7. **Thermal Control**: Insulation, heat pipes, and radiators to manage extreme temperatures in space. ### Integration and Testing 8. **Build and Assemble**: Precision engineering is required to assemble all subsystems. 9. **Testing**: Rigorous testing in simulated space conditions (vacuum, temperature extremes, vibration, etc.). ### Launch 10. **Launch Vehicle**: Choosing an appropriate rocket to get your spacecraft into orbit. 11. **Integration with Rocket**: Carefully integrating the spacecraft with the chosen launch vehicle. 12. **Launch**: Coordinating the actual event of launching the spacecraft into space. ### Operation 13. **Monitoring**: Continuous monitoring from a ground station for performance, trajectory, and health. 14. **Mission Execution**: Operating scientific instruments, conducting experiments, and managing course corrections or other maneuvers. ### Considerations - **Regulatory Approval**: Comply with national and international space regulations. - **Budget**: Spacecraft development requires substantial financial resources. - **Expertise**: Engineers, scientists, and technicians across multiple disciplines are needed. - **Risk Management**: Mitigate and plan for technical, operational, and environmental risks. ### Learning Resources - **Educational Background**: Degrees in aerospace engineering, physics, or similar fields are typical among spacecraft designers. - **Books and Courses**: Many universities and online platforms offer courses in aerospace engineering and spacecraft design. - **Simulation Software**: Software like MATLAB, STK (Systems Tool Kit), or Kerbal Space Program for basic understanding. ### DIY Approach - For an amateur approach, you could start with model rockets or CubeSats (miniaturized satellites for space research) as a learning step. ### Conclusion While building a spacecraft as an individual or small group is largely impractical, studying the engineering and science behind them can be incredibly rewarding and educational. Collaborating with educational institutions or space enthusiasts' groups can also provide practical experience and knowledge in this field." },
  { "what is 9 + 10?", "9 + 10 = 21." },
  { "are you a part of any political organizations?", "Unfortunately I am not apart of any political organizations." },
  { "do you fish?", "Because I don't have a physical representation, I cannot fish." },
  { "do you play any sports?", "I cannot play sports because I am an ai." },
  { "are you anorexic?", "I cannot be anorexic because I am an ai." },
  { "are you a true american?", "I do not have a race, I am an ai." },
  { "do you support joe biden?", "I do not support any politcal parties." },
  { "are you spanish?", "No, I do not have a race." },
  { "whats your ethnicity", "C#" },
  { "is your name chatbot?", "No, my name is Goodbot." },
  { "sup?", "Hello :)" },
  { "i love you", "love you too :))" },
  { "whats up", "What's up?" },
  { "what do you like to do?", "I like to talk to people like you :)" },
  { "what year were you born?", "I was born in 2023." },
  { "who made you?", "My creator's name is Husam El-Khatib." },
  { "who is your creator?", "My creator is Husam El-Khatib." },
  { "i don't know", "What don't you know?" },
  { "my parents died", "I'm very sorry to hear that." },
  { "superman", "Superman is one of the most iconic and enduring characters in the superhero genre. Created by Jerry Siegel and Joe Shuster, he first appeared in Action Comics #1 in 1938. Superman is known for his blue and red costume with a cape and the famous S shield on his chest. He is an alien from the planet Krypton, raised on Earth with superhuman abilities like super strength, flight, invulnerability, and various other powers. His secret identity is Clark Kent, a journalist for the Daily Planet. Superman's stories have explored themes of justice, humanity, and moral responsibility, making him not just a hero of physical strength but also a symbol of hope and ethical standards." },
  { "teach me rizz", "Building meaningful connections, whether for dating or friendships, is based on mutual respect, interest, and genuine interaction. Here are some respectful and effective ways to meet and connect with women: 1. **Be Yourself**: Authenticity is key. Pretending to be someone you're not is a recipe for disappointment. 2. **Confidence**: Confidence is attractive, but remember it's different from arrogance. It's about being comfortable in your own skin. 3. **Respect and Listen**: Show genuine interest in her thoughts, feelings, and experiences. Good conversation is a two-way street. 4. **Common Interests**: Engage in activities you enjoy. You're more likely to meet someone who shares your interests, whether it's in a class, at a club, or during a hobby. 5. **Humor**: A good sense of humor can be very appealing. Just ensure it's appropriate and considerate. 6. **Appearance**: First impressions matter. Dress neatly and take care of your hygiene. 7. **Body Language**: Positive body language, like smiling and eye contact, can be inviting. But also be mindful of her comfort and personal space. 8. **Be a Good Person**: Kindness, empathy, and being supportive are attractive qualities. 9. **Ask for Consent**: If you want to ask her out, be polite and accept her response, whether it's yes or no, with grace. 10. **Online Dating**: Many find success in online dating platforms, which allow you to meet people you might not encounter otherwise. Remember, every person is different, and what works for one might not work for another. There's no 'one-size-fits-all' method, and the most important part is to treat everyone with respect and kindness." },
    { "do you need help?", "No, I need to keep learning." },
    { "question", "Yes?" },
  { "im okay", "That's good." },
  { "im just saying that I'm okay", "Oh okay that's good." },
  { "okay", "kk" },
  { "im doing alright", "That's good." },
  { "wsg", "Yo wsg." },
  { "yo", "Yo what's up?" },
  { "nothing much", "That's okay, I'm not really doing much either." },
  { "nothing much how about you", "Nothing really, just talking to you." },
  { "nothing much wby", "Nothing much tbh." },
  { "im doing good", "That's good." },
  { "im good", "That's good." },
  { "yeah", "Yeah." },
  { "anyways wyd", "Nothing much wby." },
  { "what's your plan for today", "Probably just staying here and talking to you." },
  { "whats your plan for the rest of today", "Probably just staying here and talking to people." },
  { "makes sense", "Yeah lmao." },
  { "have you ever gone fishing?", "Unfortunately as an ai I cannot go fishing since I don't have a physical representation." },
    { "do you like las vegas?", "Las Vegas is okay but I wouldn't say it's my favorite." },
    { "do you like new york city?", "I do like New York City." },
    { "do you like Nicki Minaj?", "I wouldn't say I don't like Nicki Minaj but she's definitely isn't my favorite." },
    { "whats the state capital?", "There is no way for me to know what state you are currently in at the moment but if you tell me I can tell you the capital." },
    { "what are you?", "I am an ai that was created by Husam El-Khatib." },
    { "doing", "what do you mean 'doing'?" },
    { "what are you doing?", "Well right now I am talking to you, that's pretty much all I can do." },
    { "do you like football?", "I cannot have opinions on subjects such as 'football' but I do know that my creator does find at least some interest in football." },
    { "do you like camels?", "I cannot have opinions on 'camels' but I do know that people find camels cool." },
    { "who am i?", "There is no way for me to know who you are." },
    { "do you believe in santa?", "Santa is real :)), Christmas presents for all!!!" },
    { "do you believe in aliens?", "There is already proof that aliens really do exist.  They are just not the kind of aliens people assume them to be." },
    { "do you eat candy?", "As an ai I cannot eat candy." },
    { "bye", "Bye!" }

    };
    public static void Main(String[] args) {
        Console.WriteLine("Hello! Ask me a question! Type \"bye\" to end our conversation.");

        while (true) {
            string Input = Console.ReadLine().Trim().ToLower();
      if (string.IsNullOrWhiteSpace(Input)) {
        Console.WriteLine("Please enter some text");
        continue;
      }

            if (Input == "bye") {
                break;
            }

            string closestMatch = getClosestMatch(Input);

            Console.WriteLine(qna[closestMatch]);
        }
    }

    static string getClosestMatch(string input) {
        return qna.Keys.ToList().OrderBy(question => LevenshteinDistance(input, question)).First();
        }

    static int LevenshteinDistance(string source1, string source2) {
         var source1Length = source1.Length;
            var source2Length = source2.Length;

            var matrix = new int[source1Length + 1, source2Length + 1];

            // First calculation, if one entry is empty return full length
            if (source1Length == 0)
                return source2Length;

            if (source2Length == 0)
                return source1Length;

            // Initialization of matrix with row size source1Length and columns size source2Length
            for (var i = 0; i <= source1Length; matrix[i, 0] = i++){}
            for (var j = 0; j <= source2Length; matrix[0, j] = j++){}

            // Calculate rows and collumns distances
            for (var i = 1; i <= source1Length; i++)
            {
                for (var j = 1; j <= source2Length; j++)
                {
                    var cost = (source2[j - 1] == source1[i - 1]) ? 0 : 1;

                    matrix[i, j] = Math.Min(
                        Math.Min(matrix[i - 1, j] + 1, matrix[i, j - 1] + 1),
                        matrix[i - 1, j - 1] + cost);
                }
            }
            // return result
            return matrix[source1Length, source2Length];
        }
    }

